### ISSUE TITLE
LoopFor2.sol verification attempt

### ISSUE THREAD

**Issue by unboxedtype** [microsoft/verisol#125]
Hi!

Playing around with your tool. Please look at the snippet that, as I think, produces false positive:
```
$ cat Test/regressions/LoopFor2.sol
pragma solidity ^0.4.24;
contract LoopFor2 {
    uint[100] b;
    uint[100] c;

    function LoopFor2() public {
      b[0] = c[0];
    }
    function testUnboundedForLoop(uint n) public {
      require (n > 0 && n < 100);
      for (uint i = 0; i < n; i += 1) {
        b[i] = i + 1;
        if (n > 50) { c[i] = b[i] - 1; }
        else c[i] = b[i];
      }
    }
    function test() public { assert(b[0] == c[0]); }
}

````

Corresponding json file:
```
$ cat Test/config/LoopFor2.json
{
    "recursionBound": 8,
    "k": 1,
    "main": "CorralEntry_LoopFor2",
    "expectedResult": "Program has no bugs"
}

````
The tool reports that the test passes, but I think it should not. 
The call sequence: `testUnboundedForLoop(60);  test();  `
will result in assertion violation.
```
$ dotnet $VeriSolPath/Sources/SolToBoogieTest/bin/Debug/netcoreapp2.2/SolToBoogieTest.dll $VeriSolPath $VeriSolPath/Test/     

...

info: SolToBoogieTest.RegressionExecutor[0]
      Running LoopFor2.sol
/home/shishkin/src/verisol/corral/bin/debug/corral.exe /recursionBound:8 /k:1 /main:CorralEntry_LoopFor2 __SolToBoogieTest_out.bpl
info: SolToBoogieTest.RegressionExecutor[0]
      Passed - LoopFor2.sol
...
```

**Comment by shuvendu-lahiri** [comment]
This is expected and not an error. We currently run the regressions using a "bounded" checker (for automation) that only unrolls loops in programs and the number of transactions to "recursionBound". In this case, the test passes because we did not find any assertion failure by unrolling the loop upto 8 times. I tried changing the recursionBound to 51, but the verifier takes a long time. I was however able to find the error if I change "n > 50" to "n > 6". I added the modified example as a regression LoopFor2.sol in a [commit](https://github.com/microsoft/verisol/commit/daa2e1a2d3625b34705abd02ac9a190664de9a2a).

To use the sound verifier (that will show the failure), please use the instructions [here](https://github.com/Microsoft/verisol/blob/master/INSTALL.md#run-verifier) using "Sound Verification".  However, there is no proof since the assertion will be violated.  For cases when the assertion should not fail, one has to perform the proof in Boogie currently, but we are working on building invariant support within Solidity. 

Please close this issue if you are satisfied.

**Comment by unboxedtype** [comment]
Thanks a lot!

**Comment by unboxedtype** [comment]
Can you please explain what "k" param means? Does it have to do with the k-induction technique?

**Comment by unboxedtype** [comment]
> For cases when the assertion should not fail, one has to perform the proof in Boogie currently, but we are working on building invariant support within Solidity.

You mean that it will be possible to add invariant assertion for some loop construction and then, given that the invariant is strong enought, the tool will be able to prove a top level assertion?

**Comment by shuvendu-lahiri** [comment]
The "k" parameter only applies when using the bounded verifier Corral on multithreaded code. I should hide it from the config options as it is always fixed to 1 (number of threads). 

Your intuition about loop invariant is correct. These will be in the form of a code contract library for VeriSol.

**Comment by unboxedtype** [comment]
Thanks again for clarification! 
FWIW, Solidity compiler extension known as SMTChecker has its own invariant checking support. Making your solution compatible with SMTChecker syntax would be great.

**Comment by shuvendu-lahiri** [comment]
Thanks for the pointer! Can you point me to any documentation on language extensions to support SMTChecker in Solidity?

**Comment by unboxedtype** [comment]
Sorry, I was sure that they have already implemented invariant support for loops. Turns out, they did'nt. 
Here is an issue that is devoted to this development: https://github.com/ethereum/solidity/issues/6210
